name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'BeatSaberPlaylistsLib/**'
      - '.github/workflows/BuildMaster.yml'
  pull_request:
    branches: [ master ]
    paths: 'BeatSaberPlaylistsLib/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      id: Build
      run: dotnet build --configuration Release
    - name: Get artifact name variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: BeatSaberPlaylistsLib-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
        path: ./BeatSaberPlaylistsLib/bin/Release/
