name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'BeatSaberPlaylistsLib/**'
      - '.github/workflows/BuildMaster.yml'
  pull_request:
    branches: [ master ]
    paths: 'BeatSaberPlaylistsLib/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      id: Build
      run: dotnet build --configuration Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ./BeatSaberPlaylistsLib/bin/Release/
